
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARROW COMMA CUSTOM_OP EQUALS FAT_ARROW ID KW_COMPONENT KW_DEFSHORTCUT KW_DIGRAPH KW_GRAPH KW_STRICT LBRACE LBRACKET LPAREN RBRACE RBRACKET RPAREN SEMICOLON STRING VAR_IDprogram : strict_op KW_DIGRAPH ID LBRACE graph_body RBRACEgraph_body : graph_body statement\n                  | statementstatement : ID ARROW ID SEMICOLON\n                 | ID SEMICOLONstrict_op : KW_STRICT\n                 | emptyempty :'
    
_lr_action_items = {'KW_STRICT':([0,],[3,]),'KW_DIGRAPH':([0,2,3,4,],[-8,5,-6,-7,]),'$end':([1,13,],[0,-1,]),'ID':([5,7,9,10,11,12,14,16,],[6,8,8,-3,15,-5,-2,-4,]),'LBRACE':([6,],[7,]),'ARROW':([8,],[11,]),'SEMICOLON':([8,15,],[12,16,]),'RBRACE':([9,10,12,14,16,],[13,-3,-5,-2,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'strict_op':([0,],[2,]),'empty':([0,],[4,]),'graph_body':([7,],[9,]),'statement':([7,9,],[10,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> strict_op KW_DIGRAPH ID LBRACE graph_body RBRACE','program',6,'p_program','parser.py',6),
  ('graph_body -> graph_body statement','graph_body',2,'p_graph_body','parser.py',10),
  ('graph_body -> statement','graph_body',1,'p_graph_body','parser.py',11),
  ('statement -> ID ARROW ID SEMICOLON','statement',4,'p_statement','parser.py',18),
  ('statement -> ID SEMICOLON','statement',2,'p_statement','parser.py',19),
  ('strict_op -> KW_STRICT','strict_op',1,'p_strict_op','parser.py',32),
  ('strict_op -> empty','strict_op',1,'p_strict_op','parser.py',33),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',37),
]
