reserved = {
    "component": "KW_COMPONENT",
    "defshortcut": "KW_DEFSHORTCUT",
    "digraph": "KW_DIGRAPH",
    "strict": "KW_STRICT",
    "graph": "KW_GRAPH",
    "subgraph": "KW_SUBGRAPH",
    "node": "KW_NODE",
    "edge": "KW_EDGE",
}

tokens = (
    "ID",
    "VAR_ID",
    "STRING",
    "NUMBER",
    "ARROW",
    "FAT_ARROW",
    "EDGE_UNDIR",
    "CUSTOM_OP",
    "LBRACE",
    "RBRACE",
    "LPAREN",
    "RPAREN",
    "LBRACKET",
    "RBRACKET",
    "COMMA",
    "EQUALS",
    "SEMICOLON",
) + tuple(reserved.values())
